# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget CombBLAS::Usortlib CombBLAS::GraphGenlib CombBLAS::CombBLAS)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target CombBLAS::Usortlib
add_library(CombBLAS::Usortlib STATIC IMPORTED)

set_target_properties(CombBLAS::Usortlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/usort/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX"
)

# Create imported target CombBLAS::GraphGenlib
add_library(CombBLAS::GraphGenlib STATIC IMPORTED)

set_target_properties(CombBLAS::GraphGenlib PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/graph500-1.2/generator/include"
)

# Create imported target CombBLAS::CombBLAS
add_library(CombBLAS::CombBLAS STATIC IMPORTED)

set_target_properties(CombBLAS::CombBLAS PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "THREADED"
  INTERFACE_COMPILE_FEATURES "cxx_std_14"
  INTERFACE_INCLUDE_DIRECTORIES "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/include;/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/psort-1.0/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX;OpenMP::OpenMP_CXX;CombBLAS::Usortlib;CombBLAS::GraphGenlib"
)

# Import target "CombBLAS::Usortlib" for configuration ""
set_property(TARGET CombBLAS::Usortlib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::Usortlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/_build/usort/libUsortlib.a"
  )

# Import target "CombBLAS::GraphGenlib" for configuration ""
set_property(TARGET CombBLAS::GraphGenlib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::GraphGenlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C"
  IMPORTED_LOCATION_NOCONFIG "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/_build/graph500-1.2/generator/libGraphGenlib.a"
  )

# Import target "CombBLAS::CombBLAS" for configuration ""
set_property(TARGET CombBLAS::CombBLAS APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(CombBLAS::CombBLAS PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "C;CXX"
  IMPORTED_LOCATION_NOCONFIG "/global/homes/a/afs223/Desktop/SpGEMM-Profiling/ext/CombBLAS/_build/libCombBLAS.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
